services:
  # Services spécifiques
  App\Service\ExcelService:
    public: true

  App\Service\FusionPdf:
    public: true

  App\Service\SessionManagerService:
    public: true

  # Historique d'opération
  App\Service\historiqueOperation\HistoriqueOperationDevisMagasinService:
    arguments:
      - "@doctrine.orm.default_entity_manager"
    public: true

  App\Service\historiqueOperation\magasin\bc\HistoriqueOperationBcMagasinService:
    arguments:
      - "@doctrine.orm.default_entity_manager"
    public: true

  App\Service\fichier\UploderFileService:
    arguments:
      $cheminDeBase: "%env(BASE_PATH_FICHIER)%/magasin/devis/"
    public: true

  App\Model\LdapModel:
    public: true

  App\Controller\da\ListeDa\listeDaController:
    autowire: true
    autoconfigure: true
    arguments:
      - "@doctrine.orm.default_entity_manager"
    public: true

  App\Controller\authentification\LoginController:
    autowire: true
    autoconfigure: true
    arguments:
      - "@doctrine.orm.default_entity_manager"
      - '@App\Model\LdapModel'
    public: true

  App\Service\da\FileUploaderForDAService:
    public: true

  App\Service\da\DaService:
    arguments:
      $em: "@doctrine.orm.default_entity_manager"
      $daFileUploader: '@App\Service\da\FileUploaderForDAService'
    public: true

  App\Service\da\DaAfficherService:
    arguments:
      $em: "@doctrine.orm.default_entity_manager"
    public: true

  App\Service\da\DwDataService:
    arguments:
      $em: "@doctrine.orm.default_entity_manager"
    public: true

  App\Service\da\DaTimelineService:
    arguments:
      $em: "@doctrine.orm.default_entity_manager"
    public: true

  App\Service\da\DocRattacheService:
    arguments:
      $daService: '@App\Service\da\DaService'
      $dwDataService: '@App\Service\da\DwDataService'
    public: true

  App\Controller\da\Detail\DaDetailReapproController:
    arguments:
      $daService: '@App\Service\da\DaService'
      $docRattacheService: '@App\Service\da\DocRattacheService'
      $daTimelineService: '@App\Service\da\DaTimelineService'
    public: true

  App\Controller\da\Detail\DaDetailAvecDitController:
    arguments:
      $daTimelineService: '@App\Service\da\DaTimelineService'
    public: true

  App\Controller\da\Detail\DaDetailDirectController:
    arguments:
      $daTimelineService: '@App\Service\da\DaTimelineService'
    public: true

  App\Service\Admin\PermissionsService:
    arguments:
      $entityManager: "@doctrine.orm.default_entity_manager"
    public: true

  # Utilisateur et Profil
  App\Factory\admin\UserFactory:
    public: true

  App\Factory\admin\PermissionsFactory:
    public: true

  App\Controller\admin\UserController:
    arguments:
      - '@App\Factory\admin\UserFactory'
    public: true

  App\Controller\admin\appStructure\PermissionController:
    arguments:
      $entityManager: "@doctrine.orm.default_entity_manager"
      $permissionsService: '@App\Service\Admin\PermissionsService'
      $permissionsFactory: '@App\Factory\admin\PermissionsFactory'
    public: true
