services:
  # Services Twig
  App\Twig\AppExtension:
    arguments:
      - "@session"
      - "@request_stack"
      - "@security.token_storage"
      - "@security.authorization_checker"
    tags: ["twig.extension"]

  App\Twig\BreadcrumbExtension:
    arguments:
      - '@menu.service'
      - '@security.service'
      - '@cache.menu'
    tags: ["twig.extension"]

  App\Twig\CarbonExtension:
    tags: ["twig.extension"]

  App\Twig\DeleteWordExtension:
    tags: ["twig.extension"]
