<?php

namespace App\Mapper\Atelier\Dit;

use App\Dto\Atelier\Dit\DitDto;

class DitMapper
{
    public static function DataToBdDit(DitDto $dto)
    {
        return [
            'numero_demande_dit' => $dto->numeroDemandeIntervention,
            'type_document' => '',
            'code_societe' => $dto->codeSociete,
            'type_reparation' => $dto->typeReparation,
            'reparation_realise' => $dto->reparationRealise,
            'categorie_demande' => $dto->categorieDemande,
            'internet_externe' => $dto->internetExterne,
            'agence_service_debiteur' => '',
            'agence_service_emmeteur' => '',
            'nom_client' => $dto->nomClient,
            'date_prevue_travaux' => $dto->datePrevueTravaux,
            'demande_devis' => '',
            'id_niveau_urgence' => '',
            'avis_recouvrement' => $dto->avisRecouvrement,
            'client_sous_contrat' => $dto->clientSousContrat,
            'objet_demande' => $dto->objetDemande,
            'detail_demande' => $dto->detailDemande,
            'livraison_partiel' => $dto->livraisonPartiel,
            'id_materiel' => $dto->idMateriel,
            'mail_demandeur' => $dto->mailDemandeur,
            'date_demande' => $dto->dateDemande,
            'heure_demande' => $dto->heureDemande,
            'piece_joint1' => '',
            'piece_joint2' => '',
            'piece_joint' => '',
            'utilisateur_demandeur' => $dto->utilisateurDemandeur,
            'observations' => '',
            'id_statut_demande' => '',
            'numero_client' => $dto->numeroClient,
            'libelle_client' => '',
            'date_fin_souhaite' => '',
            'numero_or' => '',
            'observation_direction_technique' => '',
            'observation_devis' => '',
            'numero_devis_rattache' => '',
            'date_soumission_devis' => '',
            'statut_devis' => '',
            'date_validation_devis' => '',
            'id_service_intervenant' => '',
            'date_devis_fin_probable' => '',
            'date_fin_estimation_travaux' => '',
            'code_section' => '',
            'mas_ate' => '',
            'code_ate' => '',
            'secteur' => '',
            'utilisateur_intervenant' => '',
            'km_machine' => '',
            'heure_machine' => '',
            'date_devis_rattache' => '',
            'section_affectee' => '',
            'statut_or' => '',
            'statut_commande' => '',
            'date_validation_or' => '',
            'agence_emetteur_id' => '',
            'service_emetteur_id' => '',
            'agence_debiteur_id' => '',
            'service_debiteur_id' => '',
            'section_support_1' => '',
            'section_support_2' => '',
            'section_support_3' => '',
            'migration' => '',
            'etat_facturation' => '',
            'ri' => '',
            'mail_client' => '',
            'num_migr' => '',
            'a_annuler' => '',
            'date_annulation' => '',
            'numero_demande_dit_avoir' => '',
            'numero_demande_dit_refacturation' => '',
            'dit_avoir' => '',
            'dit_refacturation' => '',
            'ate_pol_tana' => '',
            'pdf_deposer_dw' => '',
            'date_depot_pdf_dw' => '',
        ];
    }
}
