CREATE TABLE Demande_Appro_P_L (
	id int IDENTITY(1,1) NOT NULL,
	numero_demande_appro varchar(11) NULL,
	num_ligne int NOT NULL,
	qte_dem int NULL,
	art_constp varchar(3) NULL,
	art_refp varchar(50) NULL,
	art_desi varchar(100) NULL,
	code_fams1 varchar(10) NULL,
	art_fams1 varchar(50) NULL,
	code_fams2 varchar(50) NULL,
	art_fams2 varchar(50) NULL,
	numero_fournisseur varchar(7) NULL,
	nom_fournisseur varchar(50) NULL,
	date_fin_souhaitee_l datetime2(0) NULL,
	commentaire varchar(1000) NULL,
	statut_dal varchar(50) NULL,
	art_stocke bit NULL,
	demande_appro_id int NULL,
	date_creation datetime2(0) NULL,
	date_modification datetime2(0) NULL,
	prix_unitaire varchar(100) NULL,
	est_fiche_technique bit NULL,
	nom_fiche_technique varchar(255) NULL,
	file_names text NULL,
	demandeur varchar(100) NULL,
    jours_dispo int NULL,
    CONSTRAINT PK_Demande_Appro_P_L PRIMARY KEY (id)
);